---
- name: Multi-Subnet IPAM + GCP Provisioning
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    env_csv: "{{ playbook_dir }}/data/Env.csv"
    subnet_csv: "{{ playbook_dir }}/data/Subnet.csv"
    calc_script: "{{ playbook_dir }}/scripts/calc_next_subnet.py"

    region_map:
      AO: asia-south1
      EU: europe-west1
      AS: asia-east1
      NA: us-central1

  tasks:

    - name: Initialize summary array
      set_fact:
        subnet_results: []

    - fail:
        msg: "'subnets' variable missing"
      when: subnets is not defined

    - fail:
        msg: "'subnets' should be a list"
      when: subnets is not iterable

    - fail:
        msg: "Max 5 subnets per execution"
      when: subnets | length > 5

    - name: Read Env.csv
      read_csv:
        path: "{{ env_csv }}"
      register: env_raw

    - set_fact:
        env_data: "{{ env_raw.list }}"

    - name: Read Subnet.csv
      read_csv:
        path: "{{ subnet_csv }}"
      register: subnet_raw

    - set_fact:
        subnet_data: "{{ subnet_raw.list }}"

    - name: Process each subnet request
      include_tasks: subnet_unit.yml
      loop: "{{ subnets }}"
      loop_control:
        loop_var: req

    #####################################################################
    # SEND EMAIL SUMMARY
    #####################################################################
    - name: Build final HTML email table
      set_fact:
        summary_html: |
          <table border="1" cellpadding="6" cellspacing="0" style="border-collapse: collapse; font-family: Arial; width: 100%;">
            <thead>
              <tr style="background-color:#4CAF50; color:white;">
                <th>Region</th>
                <th>Env</th>
                <th>Solution</th>
                <th>Subnet Name</th>
                <th>Subnet CIDR</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
            {% for item in subnet_results %}
              <tr>
                <td>{{ item.Region }}</td>
                <td>{{ item.Env }}</td>
                <td>{{ item.Solution }}</td>
                <td>{{ item.SubnetName }}</td>
                <td>{{ item.CIDR }}</td>
                <td style="color: {{ item.Color }};">{{ item.Status }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>

    - name: Send email summary
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ email_user }}"
        password: "{{ email_password }}"
        to: "{{ email_to }}"
        subject: "GCP Subnet Creation Summary Report"
        subtype: html
        body: |
          <html>
            <body>
              <p>Hello Team,<br><br>
              Below is the complete summary of the subnet creation batch:</p>
              {{ summary_html | safe }}

              <p><br>Regards,<br>Network Automation Team<br>
              <small>This is an automated email. Do not reply.</small></p>
            </body>
          </html>
