---
- name: Multi-Subnet IPAM + GCP Provisioning
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    env_csv: "{{ playbook_dir }}/data/Env.csv"
    subnet_csv: "{{ playbook_dir }}/data/Subnet.csv"
    calc_script: "{{ playbook_dir }}/scripts/calc_next_subnet.py"

    region_map:
      AO: asia-south1
      EU: europe-west1
      AS: asia-east1
      NA: us-central1

  tasks:
    - fail:
        msg: "'subnets' variable missing"
      when: subnets is not defined

    - fail:
        msg: "'subnets' should be a list"
      when: subnets is not iterable

    - fail:
        msg: "Max 5 subnets per execution"
      when: subnets | length > 5

    - name: Read Env.csv
      read_csv:
        path: "{{ env_csv }}"
      register: env_raw

    - set_fact:
        env_data: "{{ env_raw.list }}"

    - name: Read Subnet.csv
      read_csv:
        path: "{{ subnet_csv }}"
      register: subnet_raw

    - set_fact:
        subnet_data: "{{ subnet_raw.list }}"

    - name: Process each subnet request
      include_tasks: subnet_unit.yml
      loop: "{{ subnets }}"
      loop_control:
        loop_var: req

    ###################################################################
    # AFTER LOOP — BUILD SUMMARY AND SEND EMAIL
    ###################################################################

    - name: Initialize results list
      set_fact:
        subnet_results: []

    # This collects results that subnet_unit.yml stored in "subnet_results"
    # If not stored, we create empty default
    - name: Ensure subnet_results exists
      set_fact:
        subnet_results: "{{ subnet_results | default([]) }}"

    ###################################################################
    # 1. BUILD HTML SUMMARY REPORT
    ###################################################################
    - name: Build HTML summary report
      copy:
        dest: "{{ playbook_dir }}/report.html"
        content: |
          <html>
          <body>
          <h2>GCP Multi-Subnet Creation Summary</h2>
          <p>Date: {{ lookup('pipe', 'date') }}</p>

          <table border="1" cellpadding="6" cellspacing="0"
                 style="border-collapse: collapse; width: 100%; font-family: Arial;">
            <tr style="background-color: #333; color: white;">
              <th>Region</th>
              <th>Env</th>
              <th>Solution</th>
              <th>CIDR</th>
              <th>Subnet Name</th>
              <th>Status</th>
              <th>Comments</th>
            </tr>

            {% for row in subnet_results %}
            <tr>
              <td>{{ row.Region }}</td>
              <td>{{ row.Env }}</td>
              <td>{{ row.Solution }}</td>
              <td>{{ row.CIDR }}</td>
              <td>{{ row.SubnetName }}</td>
              <td style="color: {{ row.Color }}; font-weight: bold;">
                {{ row.Status }}
              </td>
              <td>{{ row.Comments }}</td>
            </tr>
            {% endfor %}
          </table>

          <p style="margin-top: 20px;">Best regards,<br>Network Automation Team</p>
          </body>
          </html>

    ###################################################################
    # 2. SEND EMAIL WITH CSV + HTML REPORT ATTACHMENTS
    ###################################################################
    - name: Email updated CSVs + HTML Summary Report
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ premgkumardc@gmail.com }}"
        password: "{{ jvpx gfpd yyta jkwe }}"
        to: "{{ premkumaransible@gmail.com }}"
        subject: "GCP Multi-Subnet Report - {{ lookup('pipe', 'date +%Y-%m-%d_%H:%M') }}"
        subtype: html
        body: |
          <html>
            <body>
              <h3>GCP Multi-Subnet Creation Summary</h3>

              <p><b>Total Requests:</b> {{ subnets | length }}</p>
              <p><b>Created:</b> {{ subnet_results | selectattr('Status','equalto','Created') | list | length }}</p>
              <p><b>Already Exists:</b> {{ subnet_results | selectattr('Status','equalto','Already Exists') | list | length }}</p>
              <p><b>Failed:</b> {{ subnet_results | selectattr('Status','equalto','Failed') | list | length }}</p>

              <p>The full detailed report is attached as <b>report.html</b>.</p>

              <p>Best regards,<br>Automation Bot</p>
            </body>
          </html>
        attachments:
          - "{{ playbook_dir }}/data/Env.csv"
          - "{{ playbook_dir }}/data/Subnet.csv"
          - "{{ playbook_dir }}/data/Main.csv"
          - "{{ playbook_dir }}/report.html"

